### ISSUE TITLE
Rewrite/Convert to python3?

### ISSUE THREAD

**Issue by KopfKrieg** [Exceen/4chan-downloader#10]
The ```2to3``` tool should automate this as far as possible. I think the script should be converted to python3 because this is the new standard, support for python2 will be dropped in near future.

**Comment by L3rchal** [comment]
I think that will take some time before python2 will be dropped, BUT it would be awesome to support python3 as well.

**Comment by Exceen** [comment]
Script is updated to be compatible with python3 if you want to check it out:
[Python2 to Python3 conversion](https://github.com/Exceen/4chan-downloader/commit/9c0b57d74ed9096655f71dd592fed73fdfa220d5)
