### ISSUE TITLE
invalid syntax?

### ISSUE THREAD

**Issue by sulejman3** [Exceen/4chan-downloader#14]
I guess I miss something very simple, but cannot figure it out, so here goes nothing

I followed the instructions to in README.md and typed

`$ python inb4404.py http://boards.4chan.org/w/thread/2096591/lain-thread-anyone-have-any-arisu`

The only result was:

`  File "inb4404.py", line 129`
`    print(line.replace(link, '-' + link), end='')`
`                                             ^`
`SyntaxError: invalid syntax`

And I'm too dumb to know if this is a typo to fix or I should use a different URL (direct one to the first pic in thread maybe?).

(After hundreds of shameful edits): also the output points at `end=''` equation, but for love of god I have no idea how to paste it here so markdown does not cut out all spaces.

**Comment by Exceen** [comment]
Are you using Python 2? That's probably your problem here if I had a guess because this script requires Python 3. I dropped Python 2 two months ago. There's an older version of the script written in Python 2 in the legacy directory in case you don't wanna switch to Python 3.

**Comment by sulejman3** [comment]
Okay, not sure what was the issue initially. Before running the script for the first time, I checked if I have python3 installed. After your comment, I installed python3-dev and did some updates. Now I did a sanity check and run
