### ISSUE TITLE
More than one thread? or a queue? 

### ISSUE THREAD

**Issue by alivefromupstairs** [Exceen/4chan-downloader#15]
a batch file perhaps.  `--batch moreThanOneThread.txt`

**Comment by Exceen** [comment]
Check the README:

> You can parse a file instead of a thread url. In this file you can put as many links as you want, you just have to make sure that there's one url per line. A line is considered to be a url if the first 4 letters of the line start with 'http'.

Each thread is then separated in its own thread.
