### ISSUE TITLE
Change Default Directory

### ISSUE THREAD

**Issue by alivefromupstairs** [Exceen/4chan-downloader#16]
I'm not versed in Python. how can I change the directory from `workpath\downloads\(board)\(thread)` to something like this `C:\Users\Me\Downloads\Video\(board)\(thread)`
Thanks.

**Comment by Exceen** [comment]
This isn't supported yet. If you still want to do this, you have to change the workpath variable. Right now it uses the directory in which the script itself is stored.
`workpath = os.path.dirname(os.path.realpath(__file__))`
