### ISSUE TITLE
multiple threads from file error

### ISSUE THREAD

**Issue by th3illu** [Exceen/4chan-downloader#19]
File "Python\Python38-32\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
Process Process-1:
  File "Python\Python38-32\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "4chdl\inb4404.py", line 44, in download_thread
    if args.use_names or os.path.exists(os.path.join(workpath, 'downloads', board, thread_tmp)):
AttributeError: 'NoneType' object has no attribute 'use_names'
Traceback (most recent call last):
  File "Python\Python38-32\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "Programs\Python\Python38-32\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "4chdl\inb4404.py", line 44, in download_thread
    if args.use_names or os.path.exists(os.path.join(workpath, 'downloads', board, thread_tmp)):
AttributeError: 'NoneType' object has no attribute 'use_names'

**Comment by Exceen** [comment]
Please download the current version of this script, don't modify anything and try again.

**Comment by nphl78** [comment]
I have the same issue could be syntax problem, can you please help? 
![Capture](https://user-images.githubusercontent.com/67562091/85959253-b7362780-b960-11ea-81bd-a76236cc9de8.PNG)

**Comment by nphl78** [comment]
> Please download the current version of this script, don't modify anything and try again.

I have the same issue. can you please help. I can download from url but can't download with .txt file that has links. all lines are url lines.


![Capture](https://user-images.githubusercontent.com/67562091/85959290-16943780-b961-11ea-81be-f7883d2d9af8.PNG)

**Comment by guydyke** [comment]
> > Please download the current version of this script, don't modify anything and try again.
> 
> I have the same issue. can you please help. I can download from url but can't download with .txt file that has links. all lines are url lines.
> 
> ![Capture](https://user-images.githubusercontent.com/67562091/85959290-16943780-b961-11ea-81be-f7883d2d9af8.PNG)

try "chmod +x  inb4404.py && ./inb4404.py https://boards.4chan.org/s/thread[UR THREAD]"

**Comment by guydyke** [comment]
> > Please download the current version of this script, don't modify anything and try again.
> 
> I have the same issue. can you please help. I can download from url but can't download with .txt file that has links. all lines are url lines.
> 
> ![Capture](https://user-images.githubusercontent.com/67562091/85959290-16943780-b961-11ea-81be-f7883d2d9af8.PNG)

try  "./inb4404.py ur.txt"

**Comment by Exceen** [comment]
How exactly are you trying to execute this script?

**Comment by ApplePie420** [comment]
Same here. Python 3.8.3 64-bit, tried standard CMD, powershell and even on Linux, gives the same error all the time. Tried running it by `python inb4404.py threads.txt`. This version of python is the only one installed so no py2 happening. 
![image](https://user-images.githubusercontent.com/21370314/91368335-18676380-e809-11ea-9683-74b5363c8935.png)

**Comment by HelpSeeker** [comment]
I believe the cause of the issue lies with how Python starts child processes on different platforms. On Unix the default start method is "fork", which creates a child process identical to the parent process. On Windows the default (and only available) start method is "spawn", which starts a fresh Python interpreter process.
https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods

**Comment by HelpSeeker** [comment]
Passing `args` as another parameter to `download_thread` fixes the issue.

**Comment by Exceen** [comment]
https://github.com/Exceen/4chan-downloader/commit/6ee7796a8a3141a31ab8c8b7b924af669bbde746
