### ISSUE TITLE
"Something went wrong"

### ISSUE THREAD

**Issue by cherioux** [Exceen/4chan-downloader#30]
Regardless of thread, board, script location, drive letter, attribute, or host machine the script returns "Something went wrong" and times out after several tries.
![image](https://user-images.githubusercontent.com/45243557/135523816-c123df9d-ebce-4c42-bbe4-8fe24598615e.png)
Above picture showing different threads and boards and different attribute flags, all three failing almost immediately.
![image](https://user-images.githubusercontent.com/45243557/135525901-0047279d-89da-4bf8-92c7-2cccdce5cf84.png)
Interestingly however it works fine on an arch install. I've tried it on two machines running Windows 10, reinstalled python 3 as well
Not entirely sure why it's dropping almost immediately on Windows. Assume this is a Windows problem, but nothing changed since I used it yesterday. will close if I find a solution to using it on windows.
sorry there isn't much information to go off of.

**Comment by onioneffect** [comment]
This was thrown by this block of code:
```py
except (urllib.error.URLError, http.client.BadStatusLine, http.client.IncompleteRead):
    if not args.less:
        log.warning('Something went wrong')
```
In hindsight, it was silly not to include a statement right there to debug what the thing that "went wrong", so I'll include it in my own fork and you maybe you can post your results here?

**Comment by cherioux** [comment]
> 
> 
> This was thrown by this block of code:
> 
> ```python
> except (urllib.error.URLError, http.client.BadStatusLine, http.client.IncompleteRead):
>     if not args.less:
>         log.warning('Something went wrong')
> ```
> 
> In hindsight, it was silly not to include a statement right there to debug what the thing that "went wrong", so I'll include it in my own fork and you maybe you can post your results here?

Here ya go:
![image](https://user-images.githubusercontent.com/45243557/135537834-d46cbe6a-908a-46a2-8876-3d931e5d45fa.png)

**Comment by onioneffect** [comment]
It's not ideal, but try using **http**://boards.4chan.org/ instead of **https**. Maybe that'll work.

**Comment by cherioux** [comment]
Nope, same thing happens unfortunately 
![image](https://user-images.githubusercontent.com/45243557/135540728-b92befcb-6292-4b90-9626-d77a7cf936e7.png)

**Comment by onioneffect** [comment]
Following some StackOverflow answers, I think you should run
```
pip install --upgrade certifi
```
This will upgrade your SSL certificates. If they're expired/corrupted, it can cause issues with urllib and Requests.

**Comment by cherioux** [comment]
Still returns the same errors.
I upgraded the certificates and still the same thing, so I went and updated pip as well, still nothing. Went and added the trusted hosts to the pip.ini file, still the same thing as well
so, overall, same thing.

**Comment by onioneffect** [comment]
Can you post the output of your
```
pip --version
```
and
```
python --version
```

**Comment by cherioux** [comment]
![image](https://user-images.githubusercontent.com/45243557/135811837-49c850a2-8b4a-42ca-afaf-f18f6f7d8d10.png)
looks like the most up to date python version is 3.9.7 so I'll probably update that in the morning if I have time and report back if all went well

**Comment by cherioux** [comment]
Little late, oops
Now returns this error after updating to Python 3.10:
![image](https://user-images.githubusercontent.com/45243557/136079725-da3d3689-d793-4131-8126-9447930f75ab.png)

pip and python versions:
![image](https://user-images.githubusercontent.com/45243557/136080224-42758ab8-2202-481b-9d8a-f8916753153c.png)

**Comment by onioneffect** [comment]
There must be a way to run the program without verifying the SSL certificates.

**Comment by Exceen** [comment]
Could you please checkout this branch and tell me if it works? You need to run the script with the added `-i`/`--ignore-ssl-verification`-flag

[https://github.com/Exceen/4chan-downloader/tree/ssl-verification](/Exceen/4chan-downloader/tree/ssl-verification)

**Comment by dridner** [comment]
File ".\inb4404.py", line 43
    if args.ignore_ssl_verification:
                                   ^
IndentationError: unindent does not match any outer indentation level

**Comment by dridner** [comment]
So I fixed the indent level, which was easy.

Got this.

Traceback (most recent call last):
  File ".\inb4404.py", line 192, in <module>
    main()
  File ".\inb4404.py", line 32, in main
    download_thread(thread, args)
  File ".\inb4404.py", line 92, in download_thread
    html_result = load(thread_link).decode('utf-8')
  File ".\inb4404.py", line 51, in load
    ctx = ssl.create_default_context()
NameError: name 'ssl' is not defined

Instead of import ssl in main(), I just declared at the top, and I don't have an issue any more.
Is there anything wrong with just import ssl always?  I'm a dev, just not a python dev.  Not sure on semantics or anything.

**Comment by Exceen** [comment]
I'm really sorry, must have somehow uploaded something wrong. I fixed these issues now.

**Comment by dridner** [comment]
Oh, guess I forgot to include that with this flag, it does indeed work!

**Comment by cherioux** [comment]
Late, but this does work!
