### ISSUE TITLE
how the fuck do i run it

### ISSUE THREAD

**Issue by Azzerzz** [Exceen/4chan-downloader#34]
when i run the shitty python file it immediately closes, and the instructions are ass and dont tell me how to run it

**Comment by onioneffect** [comment]
> when i run the shitty python file it immediately closes

You're not supposed to double-click it. [[1]](https://hashcat.net/wiki/doku.php?id=ubernoobs)

> the instructions are ass and dont tell me how to run it

Yes they do. It's on the second paragraph.

Here's a guide:

1. Find where the Python file is located
2. Open your command prompt by following [this](https://www.youtube.com/watch?v=GWv6-uKgbAg) 90-second video
3. Type `python inb4404.py [LINK HERE]`
4. Replace [LINK HERE] with the link to your thread
5. Hit ENTER

**Comment by joepatricio** [comment]
I'm running this script right now. I don't get it. Why does it save images to two folders? There's a "new" folder and a "downloads" folder. What I mean is, whats the purpose of doing this?

**Comment by sgtnasty** [comment]
See:

https://github.com/Exceen/4chan-downloader/blob/04155bd6be1ad20f233f8976afdd583fd661e251/inb4404.py#L116

**Comment by joepatricio** [comment]
I still think this is an expensive solution, storagewise. Personally, I would change this behavior since I don't see the purpose of doing it.

**Comment by Exceen** [comment]
> I still think this is an expensive solution, storagewise. Personally, I would change this behavior since I don't see the purpose of doing it.

It absolutely is. When I first started writing this script for my own, I wanted it to behave exactly like this. Then quite a few people started using it as well and nobody ever complained. So I assume that many people actually like this behaviour.

I'm not really happy with this solution for a script that is used by several people, but whenever I think about a better solution, I don't find one that I'm completely satisfied either. So if you have any real suggestions then state them.
