### ISSUE TITLE
Unknown Missing Module Causing -t (--title) To Not Work

### ISSUE THREAD

**Issue by SaifSabban** [Exceen/4chan-downloader#41]
with running a command:
>python inb4404.py -t [Thread URL]

Terminal returns with:
>Could not import the required modules! Disabling --title option...

Program continues & runs fine, but files are downloaded with non original names.

**Comment by HelpSeeker** [comment]
The --title option requires the `bs4` and `django` modules. You can install them by running
```
pip install bs4 django
```
