### ISSUE TITLE
'4chan browser' User-agent results in 403: Forbidden

### ISSUE THREAD

**Issue by CCC-anon** [Exceen/4chan-downloader#47]
It seems 4gooks got mad at your script and blocked the '4chan Browser' User-agent. 
It's been returning 
`urllib.error.HTTPError: HTTP Error 403: Forbidden`
Had to change it to a browser-like one to make it work again.
Thanks for the easy to debug script!

**Comment by Exceen** [comment]
thanks for letting me know! I just pushed a new commit to address this issue. should work flawlessly again :)
