### ISSUE TITLE
Stuck on checking the first post of the thread

### ISSUE THREAD

**Issue by elleborgo** [Exceen/4chan-downloader#7]
The script keeps "checking" the first post of the thread specified as thread_link

I'm using python 2.7.13, script doesn't work with python 3 because of an error at line 73.

**Comment by Exceen** [comment]
What do you mean exactly by checking the first post of a thread? It is supposed to check for new posts in given threads. In every thread it searches for posts in general and compares that with already gathered data. This way the script determines if there's something new and downloads it.

And of course it doesn't work with python3, it's written for python2 x)

**Comment by Exceen** [comment]
Script is updated to be compatible with python3 if you want to check it out:
[Python2 to Python3 conversion](https://github.com/Exceen/4chan-downloader/commit/9c0b57d74ed9096655f71dd592fed73fdfa220d5)
