### ISSUE TITLE
It downloads but the video comes ultra fucked

### ISSUE THREAD

**Issue by eduardomendes2** [Exceen/4chan-downloader#8]
It downloads, but I can't see nothing in the downloaded videos.

A picture of how the videos are rendered: http://imgur.com/a/vJkiR

**Comment by KopfKrieg** [comment]
The script only downloads the provided webms. Are you sure it's not an issue on your side? (Decoding  error, maybe an error with hardware acceleration? Have you tried another device for testing?)
